# Generated by Django 6.0.4 on 2026-05-23 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_delivery_domain_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Исключительная ситуация', 'verbose_name_plural': 'Исключительные ситуации'},
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='Order_order_trackin_d8c96e_idx',
            old_name='Order_order_trackin_3b3bf1_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='Order_order_status_80e097_idx',
            old_name='Order_order_status_4303ad_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='Order_order_courier_66db9e_idx',
            old_name='Order_order_courie_75989f_idx',
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Решена'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Высота, см'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Длина, см'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(verbose_name='Адрес забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Вес, кг'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Ширина, см'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID транзакции'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
    ]
