# Generated by Django 6.0.4 on 2026-05-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_issue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтвержден клиентом'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург'), ('kazan', 'Казань'), ('nizhny', 'Нижний Новгород'), ('ekb', 'Екатеринбург')], default='moscow', max_length=40, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_house',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Дом доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_report_photo',
            field=models.FileField(blank=True, upload_to='orders/reports/', verbose_name='Фотоотчет доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Улица доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_to_pickup_point',
            field=models.BooleanField(default=False, verbose_name='Доставка на пункт выдачи'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_photo',
            field=models.FileField(blank=True, help_text='Фото со всех сторон. Для документов, писем и конвертов - фото конверта или файла.', upload_to='orders/photos/', verbose_name='Фотография заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_city',
            field=models.CharField(choices=[('moscow', 'Москва'), ('spb', 'Санкт-Петербург'), ('kazan', 'Казань'), ('nizhny', 'Нижний Новгород'), ('ekb', 'Екатеринбург')], default='moscow', max_length=40, verbose_name='Город забора'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_house',
            field=models.CharField(default='', max_length=20, verbose_name='Дом забора'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_street',
            field=models.CharField(default='', max_length=150, verbose_name='Улица забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес забора'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидание'), ('waiting_courier', 'В ожидание курьера'), ('delivering', 'Доставляется'), ('delivered_pickup_point', 'Доставлен на пункт выдачи'), ('delivered_address', 'Доставлен на адрес доставки'), ('confirmed', 'Подтвержден клиентом'), ('returned', 'Возврат'), ('cancelled', 'Отменено')], default='waiting', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидание'), ('waiting_courier', 'В ожидание курьера'), ('delivering', 'Доставляется'), ('delivered_pickup_point', 'Доставлен на пункт выдачи'), ('delivered_address', 'Доставлен на адрес доставки'), ('confirmed', 'Подтвержден клиентом'), ('returned', 'Возврат'), ('cancelled', 'Отменено')], max_length=30, verbose_name='Статус'),
        ),
    ]
