# Generated by Django 6.0.4 on 2026-05-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_normalize_new_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cod_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cod_collected_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cod_transferred_to_cashdesk',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_payout_amount',
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('no_answer', 'Недозвон'), ('recipient_absent', 'Получатель отсутствует'), ('refusal', 'Отказ получателя'), ('damage', 'Повреждение'), ('wrong_address', 'Неверный адрес'), ('other', 'Другое')], max_length=30, verbose_name='Тип ситуации'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
